/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenReceiver,
  ITokenReceiverInterface,
} from "../../../../contracts/token/PrivateERC20/ITokenReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onTokenReceived",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITokenReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenReceiverInterface {
    return new Interface(_abi) as ITokenReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenReceiver {
    return new Contract(address, _abi, runner) as unknown as ITokenReceiver;
  }
}
