/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as privacyBridgeErc20Sol from "./PrivacyBridgeERC20.sol";
export type { privacyBridgeErc20Sol };
export type { PrivacyBridge } from "./PrivacyBridge";
export type { PrivacyBridgeCotiNative } from "./PrivacyBridgeCotiNative";
export type { PrivacyBridgeUSDCe } from "./PrivacyBridgeUSDCe";
export type { PrivacyBridgeUSDT } from "./PrivacyBridgeUSDT";
export type { PrivacyBridgeWADA } from "./PrivacyBridgeWADA";
export type { PrivacyBridgeWBTC } from "./PrivacyBridgeWBTC";
export type { PrivacyBridgeWETH } from "./PrivacyBridgeWETH";
export type { PrivacyBridgegCoti } from "./PrivacyBridgegCoti";
