/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as privateErc20 from "./PrivateERC20";
export type { privateErc20 };
import type * as privateErc721 from "./PrivateERC721";
export type { privateErc721 };
import type * as points from "./points";
export type { points };
