/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  CotiPriceConsumerMock,
  CotiPriceConsumerMockInterface,
} from "../../../../contracts/mocks/oracle/CotiPriceConsumerMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "base",
        type: "string",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "base",
        type: "string",
      },
    ],
    name: "getPriceWithMeta",
    outputs: [
      {
        internalType: "uint256",
        name: "rate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastUpdated",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "blockTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "metaLastUpdated",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "base",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "rate_",
        type: "uint256",
      },
    ],
    name: "setRate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sync",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610279908161001c8239f35b600080fdfe60806040908082526004918236101561001757600080fd5b600092833560e01c928363524f3889146101cb575082636f62ebfb1461014e578263c84cda0f146100d757508163f5f766b314610096575063fff6cae91461005e57600080fd5b3461009357807ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc360112610093574260015580f35b80fd5b9050346100d357817ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100d3576020906001549051908152f35b5080fd5b9091503461014a57817ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc36011261014a5780359067ffffffffffffffff82116101465761012691369101610239565b809192519283378101908282526020816024359303019020554260015580f35b8380fd5b8280fd5b9091503461014a5760207ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc36011261014a57803567ffffffffffffffff8111610146576101a360609492602092369101610239565b9283855194859384378201908152030190205490600154815192835260208301524290820152f35b919250346101465760207ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc36011261014657803567ffffffffffffffff81116102355760209461022086938593369101610239565b80918437820190815203019020549051908152f35b8480fd5b9181601f840112156102675782359167ffffffffffffffff8311610267576020838186019501011161026757565b600080fdfea164736f6c6343000814000a";

type CotiPriceConsumerMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CotiPriceConsumerMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CotiPriceConsumerMock__factory extends ContractFactory {
  constructor(...args: CotiPriceConsumerMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CotiPriceConsumerMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): CotiPriceConsumerMock__factory {
    return super.connect(runner) as CotiPriceConsumerMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CotiPriceConsumerMockInterface {
    return new Interface(_abi) as CotiPriceConsumerMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CotiPriceConsumerMock {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as CotiPriceConsumerMock;
  }
}
