/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IStdReference {
  export type ReferenceDataStruct = {
    rate: BigNumberish;
    lastUpdatedBase: BigNumberish;
    lastUpdatedQuote: BigNumberish;
  };

  export type ReferenceDataStructOutput = [
    rate: bigint,
    lastUpdatedBase: bigint,
    lastUpdatedQuote: bigint
  ] & { rate: bigint; lastUpdatedBase: bigint; lastUpdatedQuote: bigint };
}

export interface CotiPriceConsumerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_STALENESS"
      | "getPrice"
      | "getPriceData"
      | "getPriceWithMeta"
      | "maxStaleness"
      | "owner"
      | "ref"
      | "setMaxStaleness"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MaxStalenessUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_STALENESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getPriceData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceWithMeta",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "maxStaleness",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "ref", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMaxStaleness",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_STALENESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceWithMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxStaleness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ref", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxStaleness",
    data: BytesLike
  ): Result;
}

export namespace MaxStalenessUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CotiPriceConsumer extends BaseContract {
  connect(runner?: ContractRunner | null): CotiPriceConsumer;
  waitForDeployment(): Promise<this>;

  interface: CotiPriceConsumerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_STALENESS: TypedContractMethod<[], [bigint], "view">;

  getPrice: TypedContractMethod<[_base: string], [bigint], "view">;

  getPriceData: TypedContractMethod<
    [_base: string],
    [IStdReference.ReferenceDataStructOutput],
    "view"
  >;

  getPriceWithMeta: TypedContractMethod<
    [_base: string],
    [
      [bigint, bigint, bigint] & {
        rate: bigint;
        lastUpdated: bigint;
        blockTimestamp: bigint;
      }
    ],
    "view"
  >;

  maxStaleness: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ref: TypedContractMethod<[], [string], "view">;

  setMaxStaleness: TypedContractMethod<
    [_maxStaleness: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_STALENESS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[_base: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPriceData"
  ): TypedContractMethod<
    [_base: string],
    [IStdReference.ReferenceDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceWithMeta"
  ): TypedContractMethod<
    [_base: string],
    [
      [bigint, bigint, bigint] & {
        rate: bigint;
        lastUpdated: bigint;
        blockTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxStaleness"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ref"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMaxStaleness"
  ): TypedContractMethod<[_maxStaleness: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "MaxStalenessUpdated"
  ): TypedContractEvent<
    MaxStalenessUpdatedEvent.InputTuple,
    MaxStalenessUpdatedEvent.OutputTuple,
    MaxStalenessUpdatedEvent.OutputObject
  >;

  filters: {
    "MaxStalenessUpdated(uint256,uint256)": TypedContractEvent<
      MaxStalenessUpdatedEvent.InputTuple,
      MaxStalenessUpdatedEvent.OutputTuple,
      MaxStalenessUpdatedEvent.OutputObject
    >;
    MaxStalenessUpdated: TypedContractEvent<
      MaxStalenessUpdatedEvent.InputTuple,
      MaxStalenessUpdatedEvent.OutputTuple,
      MaxStalenessUpdatedEvent.OutputObject
    >;
  };
}
