/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "AccessControlEnumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControlEnumerable__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "IAccessControlEnumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControlEnumerable__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC4906",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC4906__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "DataPrivacyFramework",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DataPrivacyFramework__factory>;
    getContractFactory(
      name: "DataPrivacyFrameworkMpc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DataPrivacyFrameworkMpc__factory>;
    getContractFactory(
      name: "FixedRatioCoinDisperser",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FixedRatioCoinDisperser__factory>;
    getContractFactory(
      name: "FixedRatioCoinDisperserLeftoverS1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FixedRatioCoinDisperserLeftoverS1__factory>;
    getContractFactory(
      name: "FixedRatioCoinDisperserUnlimitedWindow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FixedRatioCoinDisperserUnlimitedWindow__factory>;
    getContractFactory(
      name: "IMintableERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMintableERC20__factory>;
    getContractFactory(
      name: "IOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOwnable__factory>;
    getContractFactory(
      name: "MintDisperser",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintDisperser__factory>;
    getContractFactory(
      name: "TokenDisperser",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenDisperser__factory>;
    getContractFactory(
      name: "PrivateMessaging",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateMessaging__factory>;
    getContractFactory(
      name: "DataPrivacyFrameworkMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DataPrivacyFrameworkMock__factory>;
    getContractFactory(
      name: "PrivateMessagingHarness",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateMessagingHarness__factory>;
    getContractFactory(
      name: "CotiPriceConsumerMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CotiPriceConsumerMock__factory>;
    getContractFactory(
      name: "ERC20DecimalsMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20DecimalsMock__factory>;
    getContractFactory(
      name: "ERC20Mock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Mock__factory>;
    getContractFactory(
      name: "EncryptedTokenReceiverMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EncryptedTokenReceiverMock__factory>;
    getContractFactory(
      name: "PrivacyBridgeERC20Mock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgeERC20Mock__factory>;
    getContractFactory(
      name: "PrivateERC20AuditorSupplyMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC20AuditorSupplyMock__factory>;
    getContractFactory(
      name: "PrivateERC20CappedMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC20CappedMock__factory>;
    getContractFactory(
      name: "PrivateERC20GtCallerMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC20GtCallerMock__factory>;
    getContractFactory(
      name: "PrivateERC20Mock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC20Mock__factory>;
    getContractFactory(
      name: "IPrivateERC20TransferAndCallEncrypted",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPrivateERC20TransferAndCallEncrypted__factory>;
    getContractFactory(
      name: "PrivateERC20ReentrantReceiverMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC20ReentrantReceiverMock__factory>;
    getContractFactory(
      name: "PublicReentrantTokenReceiverMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PublicReentrantTokenReceiverMock__factory>;
    getContractFactory(
      name: "PublicTokenReceiverBoolMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PublicTokenReceiverBoolMock__factory>;
    getContractFactory(
      name: "PublicTokenReceiverMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PublicTokenReceiverMock__factory>;
    getContractFactory(
      name: "PrivateERC721URIStorageMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC721URIStorageMock__factory>;
    getContractFactory(
      name: "Arithmetic128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Arithmetic128TestsContract__factory>;
    getContractFactory(
      name: "Arithmetic256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Arithmetic256TestsContract__factory>;
    getContractFactory(
      name: "ArithmeticTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArithmeticTestsContract__factory>;
    getContractFactory(
      name: "Bitwise128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bitwise128TestsContract__factory>;
    getContractFactory(
      name: "Bitwise256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bitwise256TestsContract__factory>;
    getContractFactory(
      name: "BitwiseTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BitwiseTestsContract__factory>;
    getContractFactory(
      name: "CheckedArithmetic128WithOverflowBitTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CheckedArithmetic128WithOverflowBitTestsContract__factory>;
    getContractFactory(
      name: "CheckedArithmetic256WithOverflowBitTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CheckedArithmetic256WithOverflowBitTestsContract__factory>;
    getContractFactory(
      name: "CheckedArithmeticWithOverflowBitTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CheckedArithmeticWithOverflowBitTestsContract__factory>;
    getContractFactory(
      name: "Comparison128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Comparison128TestsContract__factory>;
    getContractFactory(
      name: "Comparison1TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Comparison1TestsContract__factory>;
    getContractFactory(
      name: "Comparison256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Comparison256TestsContract__factory>;
    getContractFactory(
      name: "Comparison2TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Comparison2TestsContract__factory>;
    getContractFactory(
      name: "MinimalImplementation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinimalImplementation__factory>;
    getContractFactory(
      name: "MinimalProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinimalProxy__factory>;
    getContractFactory(
      name: "MinMax128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinMax128TestsContract__factory>;
    getContractFactory(
      name: "MinMax256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinMax256TestsContract__factory>;
    getContractFactory(
      name: "MinMaxTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinMaxTestsContract__factory>;
    getContractFactory(
      name: "Miscellaneous1TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Miscellaneous1TestsContract__factory>;
    getContractFactory(
      name: "MiscellaneousTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiscellaneousTestsContract__factory>;
    getContractFactory(
      name: "MpcOperations128TestContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MpcOperations128TestContract__factory>;
    getContractFactory(
      name: "MpcOperationsTestContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MpcOperationsTestContract__factory>;
    getContractFactory(
      name: "Mux128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Mux128TestsContract__factory>;
    getContractFactory(
      name: "Mux256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Mux256TestsContract__factory>;
    getContractFactory(
      name: "OffboardToUserKeyTestContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OffboardToUserKeyTestContract__factory>;
    getContractFactory(
      name: "OnBoard128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OnBoard128TestsContract__factory>;
    getContractFactory(
      name: "OnBoard256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OnBoard256TestsContract__factory>;
    getContractFactory(
      name: "PrivacyImplementationV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyImplementationV1__factory>;
    getContractFactory(
      name: "PrivacyImplementationV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyImplementationV2__factory>;
    getContractFactory(
      name: "PrivacyProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyProxy__factory>;
    getContractFactory(
      name: "Random128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Random128TestsContract__factory>;
    getContractFactory(
      name: "Random256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Random256TestsContract__factory>;
    getContractFactory(
      name: "Shift128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Shift128TestsContract__factory>;
    getContractFactory(
      name: "Shift256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Shift256TestsContract__factory>;
    getContractFactory(
      name: "ShiftTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShiftTestsContract__factory>;
    getContractFactory(
      name: "StringTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StringTestsContract__factory>;
    getContractFactory(
      name: "Transfer128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Transfer128TestsContract__factory>;
    getContractFactory(
      name: "Transfer256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Transfer256TestsContract__factory>;
    getContractFactory(
      name: "TransferScalarTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferScalarTestsContract__factory>;
    getContractFactory(
      name: "TransferTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferTestsContract__factory>;
    getContractFactory(
      name: "TransferWithAllowance128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferWithAllowance128TestsContract__factory>;
    getContractFactory(
      name: "TransferWithAllowance256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferWithAllowance256TestsContract__factory>;
    getContractFactory(
      name: "TransferWithAllowance64_16TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferWithAllowance64_16TestsContract__factory>;
    getContractFactory(
      name: "TransferWithAllowance64_32TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferWithAllowance64_32TestsContract__factory>;
    getContractFactory(
      name: "TransferWithAllowance64_64TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferWithAllowance64_64TestsContract__factory>;
    getContractFactory(
      name: "TransferWithAllowance64_8TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferWithAllowance64_8TestsContract__factory>;
    getContractFactory(
      name: "TransferWithAllowanceScalarTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferWithAllowanceScalarTestsContract__factory>;
    getContractFactory(
      name: "TransferWithAllowanceTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferWithAllowanceTestsContract__factory>;
    getContractFactory(
      name: "ValidateCiphertext128TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ValidateCiphertext128TestsContract__factory>;
    getContractFactory(
      name: "ValidateCiphertext256TestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ValidateCiphertext256TestsContract__factory>;
    getContractFactory(
      name: "ValidateCiphertextTestsContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ValidateCiphertextTestsContract__factory>;
    getContractFactory(
      name: "PrivateERC20WalletMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC20WalletMock__factory>;
    getContractFactory(
      name: "CotiNodeRewards",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CotiNodeRewards__factory>;
    getContractFactory(
      name: "IERC5192",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5192__factory>;
    getContractFactory(
      name: "SoulboundNodeNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SoulboundNodeNFT__factory>;
    getContractFactory(
      name: "AccountOnboard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccountOnboard__factory>;
    getContractFactory(
      name: "CotiPriceConsumer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CotiPriceConsumer__factory>;
    getContractFactory(
      name: "ICotiPriceConsumer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICotiPriceConsumer__factory>;
    getContractFactory(
      name: "IStdReference",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStdReference__factory>;
    getContractFactory(
      name: "PrivacyBridge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridge__factory>;
    getContractFactory(
      name: "PrivacyBridgeCotiNative",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgeCotiNative__factory>;
    getContractFactory(
      name: "IHasDecimals",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHasDecimals__factory>;
    getContractFactory(
      name: "PrivacyBridgeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgeERC20__factory>;
    getContractFactory(
      name: "PrivacyBridgegCoti",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgegCoti__factory>;
    getContractFactory(
      name: "PrivacyBridgeUSDCe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgeUSDCe__factory>;
    getContractFactory(
      name: "PrivacyBridgeUSDT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgeUSDT__factory>;
    getContractFactory(
      name: "PrivacyBridgeWADA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgeWADA__factory>;
    getContractFactory(
      name: "PrivacyBridgeWBTC",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgeWBTC__factory>;
    getContractFactory(
      name: "PrivacyBridgeWETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyBridgeWETH__factory>;
    getContractFactory(
      name: "IPrivateERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPrivateERC20__factory>;
    getContractFactory(
      name: "ITokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITokenReceiver__factory>;
    getContractFactory(
      name: "ITokenReceiverEncrypted",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITokenReceiverEncrypted__factory>;
    getContractFactory(
      name: "PrivateERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC20__factory>;
    getContractFactory(
      name: "PrivateBridgedUSDC",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateBridgedUSDC__factory>;
    getContractFactory(
      name: "PrivateCOTI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateCOTI__factory>;
    getContractFactory(
      name: "PrivateCOTITreasuryGovernanceToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateCOTITreasuryGovernanceToken__factory>;
    getContractFactory(
      name: "PrivateTetherUSD",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateTetherUSD__factory>;
    getContractFactory(
      name: "PrivateWrappedADA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateWrappedADA__factory>;
    getContractFactory(
      name: "PrivateWrappedBTC",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateWrappedBTC__factory>;
    getContractFactory(
      name: "PrivateWrappedEther",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateWrappedEther__factory>;
    getContractFactory(
      name: "IPrivateERC721URIStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPrivateERC721URIStorage__factory>;
    getContractFactory(
      name: "PrivateERC721URIStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC721URIStorage__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "PrivateERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateERC721__factory>;
    getContractFactory(
      name: "MpcCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MpcCore__factory>;
    getContractFactory(
      name: "ExtendedOperations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExtendedOperations__factory>;

    getContractAt(
      name: "AccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "AccessControlEnumerable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControlEnumerable>;
    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "IAccessControlEnumerable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControlEnumerable>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC4906",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC4906>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "DataPrivacyFramework",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DataPrivacyFramework>;
    getContractAt(
      name: "DataPrivacyFrameworkMpc",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DataPrivacyFrameworkMpc>;
    getContractAt(
      name: "FixedRatioCoinDisperser",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FixedRatioCoinDisperser>;
    getContractAt(
      name: "FixedRatioCoinDisperserLeftoverS1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FixedRatioCoinDisperserLeftoverS1>;
    getContractAt(
      name: "FixedRatioCoinDisperserUnlimitedWindow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FixedRatioCoinDisperserUnlimitedWindow>;
    getContractAt(
      name: "IMintableERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMintableERC20>;
    getContractAt(
      name: "IOwnable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IOwnable>;
    getContractAt(
      name: "MintDisperser",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MintDisperser>;
    getContractAt(
      name: "TokenDisperser",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenDisperser>;
    getContractAt(
      name: "PrivateMessaging",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateMessaging>;
    getContractAt(
      name: "DataPrivacyFrameworkMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DataPrivacyFrameworkMock>;
    getContractAt(
      name: "PrivateMessagingHarness",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateMessagingHarness>;
    getContractAt(
      name: "CotiPriceConsumerMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CotiPriceConsumerMock>;
    getContractAt(
      name: "ERC20DecimalsMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20DecimalsMock>;
    getContractAt(
      name: "ERC20Mock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Mock>;
    getContractAt(
      name: "EncryptedTokenReceiverMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EncryptedTokenReceiverMock>;
    getContractAt(
      name: "PrivacyBridgeERC20Mock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgeERC20Mock>;
    getContractAt(
      name: "PrivateERC20AuditorSupplyMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC20AuditorSupplyMock>;
    getContractAt(
      name: "PrivateERC20CappedMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC20CappedMock>;
    getContractAt(
      name: "PrivateERC20GtCallerMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC20GtCallerMock>;
    getContractAt(
      name: "PrivateERC20Mock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC20Mock>;
    getContractAt(
      name: "IPrivateERC20TransferAndCallEncrypted",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPrivateERC20TransferAndCallEncrypted>;
    getContractAt(
      name: "PrivateERC20ReentrantReceiverMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC20ReentrantReceiverMock>;
    getContractAt(
      name: "PublicReentrantTokenReceiverMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PublicReentrantTokenReceiverMock>;
    getContractAt(
      name: "PublicTokenReceiverBoolMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PublicTokenReceiverBoolMock>;
    getContractAt(
      name: "PublicTokenReceiverMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PublicTokenReceiverMock>;
    getContractAt(
      name: "PrivateERC721URIStorageMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC721URIStorageMock>;
    getContractAt(
      name: "Arithmetic128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Arithmetic128TestsContract>;
    getContractAt(
      name: "Arithmetic256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Arithmetic256TestsContract>;
    getContractAt(
      name: "ArithmeticTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArithmeticTestsContract>;
    getContractAt(
      name: "Bitwise128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Bitwise128TestsContract>;
    getContractAt(
      name: "Bitwise256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Bitwise256TestsContract>;
    getContractAt(
      name: "BitwiseTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BitwiseTestsContract>;
    getContractAt(
      name: "CheckedArithmetic128WithOverflowBitTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CheckedArithmetic128WithOverflowBitTestsContract>;
    getContractAt(
      name: "CheckedArithmetic256WithOverflowBitTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CheckedArithmetic256WithOverflowBitTestsContract>;
    getContractAt(
      name: "CheckedArithmeticWithOverflowBitTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CheckedArithmeticWithOverflowBitTestsContract>;
    getContractAt(
      name: "Comparison128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Comparison128TestsContract>;
    getContractAt(
      name: "Comparison1TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Comparison1TestsContract>;
    getContractAt(
      name: "Comparison256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Comparison256TestsContract>;
    getContractAt(
      name: "Comparison2TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Comparison2TestsContract>;
    getContractAt(
      name: "MinimalImplementation",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MinimalImplementation>;
    getContractAt(
      name: "MinimalProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MinimalProxy>;
    getContractAt(
      name: "MinMax128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MinMax128TestsContract>;
    getContractAt(
      name: "MinMax256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MinMax256TestsContract>;
    getContractAt(
      name: "MinMaxTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MinMaxTestsContract>;
    getContractAt(
      name: "Miscellaneous1TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Miscellaneous1TestsContract>;
    getContractAt(
      name: "MiscellaneousTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MiscellaneousTestsContract>;
    getContractAt(
      name: "MpcOperations128TestContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MpcOperations128TestContract>;
    getContractAt(
      name: "MpcOperationsTestContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MpcOperationsTestContract>;
    getContractAt(
      name: "Mux128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Mux128TestsContract>;
    getContractAt(
      name: "Mux256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Mux256TestsContract>;
    getContractAt(
      name: "OffboardToUserKeyTestContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OffboardToUserKeyTestContract>;
    getContractAt(
      name: "OnBoard128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OnBoard128TestsContract>;
    getContractAt(
      name: "OnBoard256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OnBoard256TestsContract>;
    getContractAt(
      name: "PrivacyImplementationV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyImplementationV1>;
    getContractAt(
      name: "PrivacyImplementationV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyImplementationV2>;
    getContractAt(
      name: "PrivacyProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyProxy>;
    getContractAt(
      name: "Random128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Random128TestsContract>;
    getContractAt(
      name: "Random256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Random256TestsContract>;
    getContractAt(
      name: "Shift128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Shift128TestsContract>;
    getContractAt(
      name: "Shift256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Shift256TestsContract>;
    getContractAt(
      name: "ShiftTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ShiftTestsContract>;
    getContractAt(
      name: "StringTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StringTestsContract>;
    getContractAt(
      name: "Transfer128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Transfer128TestsContract>;
    getContractAt(
      name: "Transfer256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Transfer256TestsContract>;
    getContractAt(
      name: "TransferScalarTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferScalarTestsContract>;
    getContractAt(
      name: "TransferTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferTestsContract>;
    getContractAt(
      name: "TransferWithAllowance128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferWithAllowance128TestsContract>;
    getContractAt(
      name: "TransferWithAllowance256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferWithAllowance256TestsContract>;
    getContractAt(
      name: "TransferWithAllowance64_16TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferWithAllowance64_16TestsContract>;
    getContractAt(
      name: "TransferWithAllowance64_32TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferWithAllowance64_32TestsContract>;
    getContractAt(
      name: "TransferWithAllowance64_64TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferWithAllowance64_64TestsContract>;
    getContractAt(
      name: "TransferWithAllowance64_8TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferWithAllowance64_8TestsContract>;
    getContractAt(
      name: "TransferWithAllowanceScalarTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferWithAllowanceScalarTestsContract>;
    getContractAt(
      name: "TransferWithAllowanceTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferWithAllowanceTestsContract>;
    getContractAt(
      name: "ValidateCiphertext128TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ValidateCiphertext128TestsContract>;
    getContractAt(
      name: "ValidateCiphertext256TestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ValidateCiphertext256TestsContract>;
    getContractAt(
      name: "ValidateCiphertextTestsContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ValidateCiphertextTestsContract>;
    getContractAt(
      name: "PrivateERC20WalletMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC20WalletMock>;
    getContractAt(
      name: "CotiNodeRewards",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CotiNodeRewards>;
    getContractAt(
      name: "IERC5192",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5192>;
    getContractAt(
      name: "SoulboundNodeNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SoulboundNodeNFT>;
    getContractAt(
      name: "AccountOnboard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccountOnboard>;
    getContractAt(
      name: "CotiPriceConsumer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CotiPriceConsumer>;
    getContractAt(
      name: "ICotiPriceConsumer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICotiPriceConsumer>;
    getContractAt(
      name: "IStdReference",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStdReference>;
    getContractAt(
      name: "PrivacyBridge",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridge>;
    getContractAt(
      name: "PrivacyBridgeCotiNative",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgeCotiNative>;
    getContractAt(
      name: "IHasDecimals",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHasDecimals>;
    getContractAt(
      name: "PrivacyBridgeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgeERC20>;
    getContractAt(
      name: "PrivacyBridgegCoti",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgegCoti>;
    getContractAt(
      name: "PrivacyBridgeUSDCe",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgeUSDCe>;
    getContractAt(
      name: "PrivacyBridgeUSDT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgeUSDT>;
    getContractAt(
      name: "PrivacyBridgeWADA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgeWADA>;
    getContractAt(
      name: "PrivacyBridgeWBTC",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgeWBTC>;
    getContractAt(
      name: "PrivacyBridgeWETH",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyBridgeWETH>;
    getContractAt(
      name: "IPrivateERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPrivateERC20>;
    getContractAt(
      name: "ITokenReceiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITokenReceiver>;
    getContractAt(
      name: "ITokenReceiverEncrypted",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITokenReceiverEncrypted>;
    getContractAt(
      name: "PrivateERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC20>;
    getContractAt(
      name: "PrivateBridgedUSDC",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateBridgedUSDC>;
    getContractAt(
      name: "PrivateCOTI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateCOTI>;
    getContractAt(
      name: "PrivateCOTITreasuryGovernanceToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateCOTITreasuryGovernanceToken>;
    getContractAt(
      name: "PrivateTetherUSD",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateTetherUSD>;
    getContractAt(
      name: "PrivateWrappedADA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateWrappedADA>;
    getContractAt(
      name: "PrivateWrappedBTC",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateWrappedBTC>;
    getContractAt(
      name: "PrivateWrappedEther",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateWrappedEther>;
    getContractAt(
      name: "IPrivateERC721URIStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPrivateERC721URIStorage>;
    getContractAt(
      name: "PrivateERC721URIStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC721URIStorage>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "PrivateERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateERC721>;
    getContractAt(
      name: "MpcCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MpcCore>;
    getContractAt(
      name: "ExtendedOperations",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ExtendedOperations>;

    deployContract(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "AccessControlEnumerable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControlEnumerable>;
    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "IAccessControlEnumerable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControlEnumerable>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC4906",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4906>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "DataPrivacyFramework",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DataPrivacyFramework>;
    deployContract(
      name: "DataPrivacyFrameworkMpc",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DataPrivacyFrameworkMpc>;
    deployContract(
      name: "FixedRatioCoinDisperser",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedRatioCoinDisperser>;
    deployContract(
      name: "FixedRatioCoinDisperserLeftoverS1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedRatioCoinDisperserLeftoverS1>;
    deployContract(
      name: "FixedRatioCoinDisperserUnlimitedWindow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedRatioCoinDisperserUnlimitedWindow>;
    deployContract(
      name: "IMintableERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMintableERC20>;
    deployContract(
      name: "IOwnable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOwnable>;
    deployContract(
      name: "MintDisperser",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MintDisperser>;
    deployContract(
      name: "TokenDisperser",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenDisperser>;
    deployContract(
      name: "PrivateMessaging",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateMessaging>;
    deployContract(
      name: "DataPrivacyFrameworkMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DataPrivacyFrameworkMock>;
    deployContract(
      name: "PrivateMessagingHarness",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateMessagingHarness>;
    deployContract(
      name: "CotiPriceConsumerMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CotiPriceConsumerMock>;
    deployContract(
      name: "ERC20DecimalsMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20DecimalsMock>;
    deployContract(
      name: "ERC20Mock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Mock>;
    deployContract(
      name: "EncryptedTokenReceiverMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EncryptedTokenReceiverMock>;
    deployContract(
      name: "PrivacyBridgeERC20Mock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeERC20Mock>;
    deployContract(
      name: "PrivateERC20AuditorSupplyMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20AuditorSupplyMock>;
    deployContract(
      name: "PrivateERC20CappedMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20CappedMock>;
    deployContract(
      name: "PrivateERC20GtCallerMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20GtCallerMock>;
    deployContract(
      name: "PrivateERC20Mock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20Mock>;
    deployContract(
      name: "IPrivateERC20TransferAndCallEncrypted",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrivateERC20TransferAndCallEncrypted>;
    deployContract(
      name: "PrivateERC20ReentrantReceiverMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20ReentrantReceiverMock>;
    deployContract(
      name: "PublicReentrantTokenReceiverMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PublicReentrantTokenReceiverMock>;
    deployContract(
      name: "PublicTokenReceiverBoolMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PublicTokenReceiverBoolMock>;
    deployContract(
      name: "PublicTokenReceiverMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PublicTokenReceiverMock>;
    deployContract(
      name: "PrivateERC721URIStorageMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC721URIStorageMock>;
    deployContract(
      name: "Arithmetic128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Arithmetic128TestsContract>;
    deployContract(
      name: "Arithmetic256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Arithmetic256TestsContract>;
    deployContract(
      name: "ArithmeticTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArithmeticTestsContract>;
    deployContract(
      name: "Bitwise128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bitwise128TestsContract>;
    deployContract(
      name: "Bitwise256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bitwise256TestsContract>;
    deployContract(
      name: "BitwiseTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BitwiseTestsContract>;
    deployContract(
      name: "CheckedArithmetic128WithOverflowBitTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CheckedArithmetic128WithOverflowBitTestsContract>;
    deployContract(
      name: "CheckedArithmetic256WithOverflowBitTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CheckedArithmetic256WithOverflowBitTestsContract>;
    deployContract(
      name: "CheckedArithmeticWithOverflowBitTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CheckedArithmeticWithOverflowBitTestsContract>;
    deployContract(
      name: "Comparison128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Comparison128TestsContract>;
    deployContract(
      name: "Comparison1TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Comparison1TestsContract>;
    deployContract(
      name: "Comparison256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Comparison256TestsContract>;
    deployContract(
      name: "Comparison2TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Comparison2TestsContract>;
    deployContract(
      name: "MinimalImplementation",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinimalImplementation>;
    deployContract(
      name: "MinimalProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinimalProxy>;
    deployContract(
      name: "MinMax128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinMax128TestsContract>;
    deployContract(
      name: "MinMax256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinMax256TestsContract>;
    deployContract(
      name: "MinMaxTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinMaxTestsContract>;
    deployContract(
      name: "Miscellaneous1TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Miscellaneous1TestsContract>;
    deployContract(
      name: "MiscellaneousTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MiscellaneousTestsContract>;
    deployContract(
      name: "MpcOperations128TestContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MpcOperations128TestContract>;
    deployContract(
      name: "MpcOperationsTestContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MpcOperationsTestContract>;
    deployContract(
      name: "Mux128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Mux128TestsContract>;
    deployContract(
      name: "Mux256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Mux256TestsContract>;
    deployContract(
      name: "OffboardToUserKeyTestContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OffboardToUserKeyTestContract>;
    deployContract(
      name: "OnBoard128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OnBoard128TestsContract>;
    deployContract(
      name: "OnBoard256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OnBoard256TestsContract>;
    deployContract(
      name: "PrivacyImplementationV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyImplementationV1>;
    deployContract(
      name: "PrivacyImplementationV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyImplementationV2>;
    deployContract(
      name: "PrivacyProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyProxy>;
    deployContract(
      name: "Random128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Random128TestsContract>;
    deployContract(
      name: "Random256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Random256TestsContract>;
    deployContract(
      name: "Shift128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Shift128TestsContract>;
    deployContract(
      name: "Shift256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Shift256TestsContract>;
    deployContract(
      name: "ShiftTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShiftTestsContract>;
    deployContract(
      name: "StringTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StringTestsContract>;
    deployContract(
      name: "Transfer128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Transfer128TestsContract>;
    deployContract(
      name: "Transfer256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Transfer256TestsContract>;
    deployContract(
      name: "TransferScalarTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferScalarTestsContract>;
    deployContract(
      name: "TransferTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferTestsContract>;
    deployContract(
      name: "TransferWithAllowance128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance128TestsContract>;
    deployContract(
      name: "TransferWithAllowance256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance256TestsContract>;
    deployContract(
      name: "TransferWithAllowance64_16TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance64_16TestsContract>;
    deployContract(
      name: "TransferWithAllowance64_32TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance64_32TestsContract>;
    deployContract(
      name: "TransferWithAllowance64_64TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance64_64TestsContract>;
    deployContract(
      name: "TransferWithAllowance64_8TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance64_8TestsContract>;
    deployContract(
      name: "TransferWithAllowanceScalarTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowanceScalarTestsContract>;
    deployContract(
      name: "TransferWithAllowanceTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowanceTestsContract>;
    deployContract(
      name: "ValidateCiphertext128TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ValidateCiphertext128TestsContract>;
    deployContract(
      name: "ValidateCiphertext256TestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ValidateCiphertext256TestsContract>;
    deployContract(
      name: "ValidateCiphertextTestsContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ValidateCiphertextTestsContract>;
    deployContract(
      name: "PrivateERC20WalletMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20WalletMock>;
    deployContract(
      name: "CotiNodeRewards",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CotiNodeRewards>;
    deployContract(
      name: "IERC5192",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5192>;
    deployContract(
      name: "SoulboundNodeNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SoulboundNodeNFT>;
    deployContract(
      name: "AccountOnboard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccountOnboard>;
    deployContract(
      name: "CotiPriceConsumer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CotiPriceConsumer>;
    deployContract(
      name: "ICotiPriceConsumer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICotiPriceConsumer>;
    deployContract(
      name: "IStdReference",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStdReference>;
    deployContract(
      name: "PrivacyBridge",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridge>;
    deployContract(
      name: "PrivacyBridgeCotiNative",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeCotiNative>;
    deployContract(
      name: "IHasDecimals",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHasDecimals>;
    deployContract(
      name: "PrivacyBridgeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeERC20>;
    deployContract(
      name: "PrivacyBridgegCoti",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgegCoti>;
    deployContract(
      name: "PrivacyBridgeUSDCe",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeUSDCe>;
    deployContract(
      name: "PrivacyBridgeUSDT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeUSDT>;
    deployContract(
      name: "PrivacyBridgeWADA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeWADA>;
    deployContract(
      name: "PrivacyBridgeWBTC",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeWBTC>;
    deployContract(
      name: "PrivacyBridgeWETH",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeWETH>;
    deployContract(
      name: "IPrivateERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrivateERC20>;
    deployContract(
      name: "ITokenReceiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITokenReceiver>;
    deployContract(
      name: "ITokenReceiverEncrypted",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITokenReceiverEncrypted>;
    deployContract(
      name: "PrivateERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20>;
    deployContract(
      name: "PrivateBridgedUSDC",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateBridgedUSDC>;
    deployContract(
      name: "PrivateCOTI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateCOTI>;
    deployContract(
      name: "PrivateCOTITreasuryGovernanceToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateCOTITreasuryGovernanceToken>;
    deployContract(
      name: "PrivateTetherUSD",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateTetherUSD>;
    deployContract(
      name: "PrivateWrappedADA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateWrappedADA>;
    deployContract(
      name: "PrivateWrappedBTC",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateWrappedBTC>;
    deployContract(
      name: "PrivateWrappedEther",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateWrappedEther>;
    deployContract(
      name: "IPrivateERC721URIStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrivateERC721URIStorage>;
    deployContract(
      name: "PrivateERC721URIStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC721URIStorage>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "PrivateERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC721>;
    deployContract(
      name: "MpcCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MpcCore>;
    deployContract(
      name: "ExtendedOperations",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExtendedOperations>;

    deployContract(
      name: "AccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "AccessControlEnumerable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControlEnumerable>;
    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "IAccessControlEnumerable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControlEnumerable>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC4906",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4906>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "DataPrivacyFramework",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DataPrivacyFramework>;
    deployContract(
      name: "DataPrivacyFrameworkMpc",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DataPrivacyFrameworkMpc>;
    deployContract(
      name: "FixedRatioCoinDisperser",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedRatioCoinDisperser>;
    deployContract(
      name: "FixedRatioCoinDisperserLeftoverS1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedRatioCoinDisperserLeftoverS1>;
    deployContract(
      name: "FixedRatioCoinDisperserUnlimitedWindow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedRatioCoinDisperserUnlimitedWindow>;
    deployContract(
      name: "IMintableERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMintableERC20>;
    deployContract(
      name: "IOwnable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOwnable>;
    deployContract(
      name: "MintDisperser",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MintDisperser>;
    deployContract(
      name: "TokenDisperser",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenDisperser>;
    deployContract(
      name: "PrivateMessaging",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateMessaging>;
    deployContract(
      name: "DataPrivacyFrameworkMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DataPrivacyFrameworkMock>;
    deployContract(
      name: "PrivateMessagingHarness",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateMessagingHarness>;
    deployContract(
      name: "CotiPriceConsumerMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CotiPriceConsumerMock>;
    deployContract(
      name: "ERC20DecimalsMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20DecimalsMock>;
    deployContract(
      name: "ERC20Mock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Mock>;
    deployContract(
      name: "EncryptedTokenReceiverMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EncryptedTokenReceiverMock>;
    deployContract(
      name: "PrivacyBridgeERC20Mock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeERC20Mock>;
    deployContract(
      name: "PrivateERC20AuditorSupplyMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20AuditorSupplyMock>;
    deployContract(
      name: "PrivateERC20CappedMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20CappedMock>;
    deployContract(
      name: "PrivateERC20GtCallerMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20GtCallerMock>;
    deployContract(
      name: "PrivateERC20Mock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20Mock>;
    deployContract(
      name: "IPrivateERC20TransferAndCallEncrypted",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrivateERC20TransferAndCallEncrypted>;
    deployContract(
      name: "PrivateERC20ReentrantReceiverMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20ReentrantReceiverMock>;
    deployContract(
      name: "PublicReentrantTokenReceiverMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PublicReentrantTokenReceiverMock>;
    deployContract(
      name: "PublicTokenReceiverBoolMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PublicTokenReceiverBoolMock>;
    deployContract(
      name: "PublicTokenReceiverMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PublicTokenReceiverMock>;
    deployContract(
      name: "PrivateERC721URIStorageMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC721URIStorageMock>;
    deployContract(
      name: "Arithmetic128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Arithmetic128TestsContract>;
    deployContract(
      name: "Arithmetic256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Arithmetic256TestsContract>;
    deployContract(
      name: "ArithmeticTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArithmeticTestsContract>;
    deployContract(
      name: "Bitwise128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bitwise128TestsContract>;
    deployContract(
      name: "Bitwise256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bitwise256TestsContract>;
    deployContract(
      name: "BitwiseTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BitwiseTestsContract>;
    deployContract(
      name: "CheckedArithmetic128WithOverflowBitTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CheckedArithmetic128WithOverflowBitTestsContract>;
    deployContract(
      name: "CheckedArithmetic256WithOverflowBitTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CheckedArithmetic256WithOverflowBitTestsContract>;
    deployContract(
      name: "CheckedArithmeticWithOverflowBitTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CheckedArithmeticWithOverflowBitTestsContract>;
    deployContract(
      name: "Comparison128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Comparison128TestsContract>;
    deployContract(
      name: "Comparison1TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Comparison1TestsContract>;
    deployContract(
      name: "Comparison256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Comparison256TestsContract>;
    deployContract(
      name: "Comparison2TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Comparison2TestsContract>;
    deployContract(
      name: "MinimalImplementation",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinimalImplementation>;
    deployContract(
      name: "MinimalProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinimalProxy>;
    deployContract(
      name: "MinMax128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinMax128TestsContract>;
    deployContract(
      name: "MinMax256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinMax256TestsContract>;
    deployContract(
      name: "MinMaxTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MinMaxTestsContract>;
    deployContract(
      name: "Miscellaneous1TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Miscellaneous1TestsContract>;
    deployContract(
      name: "MiscellaneousTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MiscellaneousTestsContract>;
    deployContract(
      name: "MpcOperations128TestContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MpcOperations128TestContract>;
    deployContract(
      name: "MpcOperationsTestContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MpcOperationsTestContract>;
    deployContract(
      name: "Mux128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Mux128TestsContract>;
    deployContract(
      name: "Mux256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Mux256TestsContract>;
    deployContract(
      name: "OffboardToUserKeyTestContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OffboardToUserKeyTestContract>;
    deployContract(
      name: "OnBoard128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OnBoard128TestsContract>;
    deployContract(
      name: "OnBoard256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OnBoard256TestsContract>;
    deployContract(
      name: "PrivacyImplementationV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyImplementationV1>;
    deployContract(
      name: "PrivacyImplementationV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyImplementationV2>;
    deployContract(
      name: "PrivacyProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyProxy>;
    deployContract(
      name: "Random128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Random128TestsContract>;
    deployContract(
      name: "Random256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Random256TestsContract>;
    deployContract(
      name: "Shift128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Shift128TestsContract>;
    deployContract(
      name: "Shift256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Shift256TestsContract>;
    deployContract(
      name: "ShiftTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShiftTestsContract>;
    deployContract(
      name: "StringTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StringTestsContract>;
    deployContract(
      name: "Transfer128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Transfer128TestsContract>;
    deployContract(
      name: "Transfer256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Transfer256TestsContract>;
    deployContract(
      name: "TransferScalarTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferScalarTestsContract>;
    deployContract(
      name: "TransferTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferTestsContract>;
    deployContract(
      name: "TransferWithAllowance128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance128TestsContract>;
    deployContract(
      name: "TransferWithAllowance256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance256TestsContract>;
    deployContract(
      name: "TransferWithAllowance64_16TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance64_16TestsContract>;
    deployContract(
      name: "TransferWithAllowance64_32TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance64_32TestsContract>;
    deployContract(
      name: "TransferWithAllowance64_64TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance64_64TestsContract>;
    deployContract(
      name: "TransferWithAllowance64_8TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowance64_8TestsContract>;
    deployContract(
      name: "TransferWithAllowanceScalarTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowanceScalarTestsContract>;
    deployContract(
      name: "TransferWithAllowanceTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferWithAllowanceTestsContract>;
    deployContract(
      name: "ValidateCiphertext128TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ValidateCiphertext128TestsContract>;
    deployContract(
      name: "ValidateCiphertext256TestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ValidateCiphertext256TestsContract>;
    deployContract(
      name: "ValidateCiphertextTestsContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ValidateCiphertextTestsContract>;
    deployContract(
      name: "PrivateERC20WalletMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20WalletMock>;
    deployContract(
      name: "CotiNodeRewards",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CotiNodeRewards>;
    deployContract(
      name: "IERC5192",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5192>;
    deployContract(
      name: "SoulboundNodeNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SoulboundNodeNFT>;
    deployContract(
      name: "AccountOnboard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccountOnboard>;
    deployContract(
      name: "CotiPriceConsumer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CotiPriceConsumer>;
    deployContract(
      name: "ICotiPriceConsumer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICotiPriceConsumer>;
    deployContract(
      name: "IStdReference",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStdReference>;
    deployContract(
      name: "PrivacyBridge",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridge>;
    deployContract(
      name: "PrivacyBridgeCotiNative",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeCotiNative>;
    deployContract(
      name: "IHasDecimals",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHasDecimals>;
    deployContract(
      name: "PrivacyBridgeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeERC20>;
    deployContract(
      name: "PrivacyBridgegCoti",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgegCoti>;
    deployContract(
      name: "PrivacyBridgeUSDCe",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeUSDCe>;
    deployContract(
      name: "PrivacyBridgeUSDT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeUSDT>;
    deployContract(
      name: "PrivacyBridgeWADA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeWADA>;
    deployContract(
      name: "PrivacyBridgeWBTC",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeWBTC>;
    deployContract(
      name: "PrivacyBridgeWETH",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyBridgeWETH>;
    deployContract(
      name: "IPrivateERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrivateERC20>;
    deployContract(
      name: "ITokenReceiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITokenReceiver>;
    deployContract(
      name: "ITokenReceiverEncrypted",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITokenReceiverEncrypted>;
    deployContract(
      name: "PrivateERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC20>;
    deployContract(
      name: "PrivateBridgedUSDC",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateBridgedUSDC>;
    deployContract(
      name: "PrivateCOTI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateCOTI>;
    deployContract(
      name: "PrivateCOTITreasuryGovernanceToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateCOTITreasuryGovernanceToken>;
    deployContract(
      name: "PrivateTetherUSD",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateTetherUSD>;
    deployContract(
      name: "PrivateWrappedADA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateWrappedADA>;
    deployContract(
      name: "PrivateWrappedBTC",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateWrappedBTC>;
    deployContract(
      name: "PrivateWrappedEther",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateWrappedEther>;
    deployContract(
      name: "IPrivateERC721URIStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPrivateERC721URIStorage>;
    deployContract(
      name: "PrivateERC721URIStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC721URIStorage>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "PrivateERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateERC721>;
    deployContract(
      name: "MpcCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MpcCore>;
    deployContract(
      name: "ExtendedOperations",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExtendedOperations>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
