/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as privateErc20 from "./PrivateERC20";
export * as privateErc721 from "./PrivateERC721";
export * as points from "./points";
